[package]
name = "todo_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http_server_tiny = "0.1.5"
serde = {version ="*", features = ["derive"]}
serde_json = "1.0.93"

